install.packages("rlang", version = '1.0.0')
install.packages("DBI")
install.packages("odbc")

install.packages("shiny")
install.packages("shinydashboard")
install.packages("shinyWidgets")
install.packages("shinycssloaders")
install.packages("shinyjs")
install.packages("dplyr")

install.packages("plotly")
install.packages("ggplot2")
install.packages("DT")

install.packages("stringr")
install.packages("stringi")
install.packages("tidyr")
install.packages("lubridate")
install.packages("glue")
install.packages("scales")
install.packages('tidymodels')